services:
  - type: web
    name: deepfake-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PORT
        value: 10000